import { Boxes, ChevronLeft, ChevronRight, FolderKanban, LayoutDashboard, Settings, ShoppingCart, UserRound, Users, X } from 'lucide-react';
import { Button } from '../components/ui/Button.jsx';

const groups = [
    { label: 'Workspace', items: [{ key: 'dashboard', activePages: ['dashboard'], label: 'Dashboard', icon: LayoutDashboard, roles: ['ADMIN', 'Ventas', 'Control Stock', null] }] },
    { label: 'Operación', items: [{ key: 'ventas', activePages: ['ventas.index', 'ventas.pos', 'ventas.show'], label: 'Ventas', icon: ShoppingCart, roles: ['ADMIN', 'Ventas'] }, { key: 'productos', activePages: ['productos.index', 'productos.create', 'productos.edit'], label: 'Productos', icon: Boxes, roles: ['ADMIN', 'Control Stock'] }, { key: 'categorias', activePages: ['categorias.index', 'categorias.create'], label: 'Categorías', icon: FolderKanban, roles: ['ADMIN', 'Control Stock'] }] },
    { label: 'Administración', items: [{ key: 'users', activePages: ['admin.users.index', 'admin.users.create', 'admin.users.edit'], label: 'Usuarios', icon: Users, roles: ['ADMIN'] }] },
];

export function Sidebar({ user, routes, activePage, open, onClose, mobileClosed, collapsed, onToggleCollapse }) {
    const visible = groups.map((group) => ({ ...group, items: group.items.filter((item) => item.roles.includes(user.role)) })).filter((group) => group.items.length);
    return <aside id="main-navigation" aria-label="Navegación principal" aria-hidden={mobileClosed || undefined} className={`fixed inset-y-0 left-0 z-40 flex h-dvh min-h-screen w-72 transform flex-col bg-sidebar text-white transition-[width,transform] duration-200 ${collapsed ? 'lg:w-[4.5rem]' : 'lg:w-72'} ${open ? 'translate-x-0' : '-translate-x-full'} lg:translate-x-0`}>
        <div className={`flex min-h-16 items-center justify-between border-b border-white/10 px-5 ${collapsed ? 'lg:justify-center lg:px-0' : ''}`}><a href={routes.dashboard} className={`flex min-h-11 items-center gap-3 font-bold tracking-tight ${collapsed ? 'lg:sr-only' : ''}`} aria-label="TiendaStock, Dashboard" tabIndex={mobileClosed ? -1 : undefined}><img src="/images/tiendastock-mark.svg" alt="" className="h-7 w-7 object-contain" /><span className="text-lg">TiendaStock</span></a><button type="button" onClick={onToggleCollapse} aria-label={collapsed ? 'Expandir barra lateral' : 'Contraer barra lateral'} aria-expanded={!collapsed} aria-controls="main-navigation" className="hidden h-11 w-11 shrink-0 place-items-center rounded-control text-white/75 transition-colors hover:bg-white/10 hover:text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white lg:grid">{collapsed ? <ChevronRight size={20} aria-hidden="true" /> : <ChevronLeft size={20} aria-hidden="true" />}</button><Button variant="icon" className="text-white lg:hidden" onClick={onClose} aria-label="Cerrar navegación" tabIndex={mobileClosed ? -1 : undefined}><X size={22} /></Button></div>
            <nav className={`flex-1 space-y-6 overflow-y-auto px-3 py-6 ${collapsed ? 'lg:px-2' : ''}`}>{visible.map((group) => <div key={group.label}><p className={`px-3 text-xs font-semibold uppercase tracking-widest text-white/60 ${collapsed ? 'lg:sr-only' : ''}`}>{group.label}</p><div className="mt-2 space-y-1">{group.items.map(({ key, activePages, label, icon: Icon }) => { const isActive = activePages.includes(activePage); return <a key={key} href={routes[key]} aria-label={label} title={collapsed ? label : undefined} aria-current={isActive ? 'page' : undefined} tabIndex={mobileClosed ? -1 : undefined} onClick={onClose} className={`flex min-h-11 items-center gap-3 rounded-control px-3 text-sm font-semibold transition-colors ${collapsed ? 'lg:justify-center lg:px-0' : ''} ${isActive ? 'bg-primary-container text-white' : 'text-white/75 hover:bg-white/10 hover:text-white'}`}><Icon size={19} aria-hidden="true" /><span className={collapsed ? 'lg:sr-only' : ''}>{label}</span></a>; })}</div></div>)}</nav>
            <a href="/profile" onClick={onClose} tabIndex={mobileClosed ? -1 : undefined} title={collapsed ? 'Configuración de cuenta' : undefined} aria-label={`Configuración de cuenta para ${user.name} (@${user.username})`} className={`mt-auto border-t flex min-h-11 items-center gap-3 rounded-control bg-white/10 px-4 py-4 text-white transition-colors hover:bg-white/15 ${collapsed ? 'lg:justify-center lg:gap-1 lg:px-0' : ''}`}><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-full bg-primary text-white ${collapsed ? 'lg:h-8 lg:w-8' : ''}`}><UserRound size={18} aria-hidden="true" /></span><span className={`min-w-0 flex-1 ${collapsed ? 'lg:sr-only' : ''}`}><span className="block truncate text-sm font-semibold">{user.name}</span><span className="block truncate text-xs text-white/60">@{user.username}</span></span><Settings className="h-4 w-4 shrink-0 text-white/60" aria-hidden="true" /></a>
    </aside>;
}
